// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "update_value_int.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic update_value_int::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic update_value_int::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<7> update_value_int::ap_ST_fsm_state1 = "1";
const sc_lv<7> update_value_int::ap_ST_fsm_state2 = "10";
const sc_lv<7> update_value_int::ap_ST_fsm_state3 = "100";
const sc_lv<7> update_value_int::ap_ST_fsm_state4 = "1000";
const sc_lv<7> update_value_int::ap_ST_fsm_state5 = "10000";
const sc_lv<7> update_value_int::ap_ST_fsm_state6 = "100000";
const sc_lv<7> update_value_int::ap_ST_fsm_state7 = "1000000";
const sc_lv<32> update_value_int::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> update_value_int::ap_const_lv32_1 = "1";
const sc_lv<32> update_value_int::ap_const_lv32_2 = "10";
const sc_lv<1> update_value_int::ap_const_lv1_0 = "0";
const sc_lv<32> update_value_int::ap_const_lv32_4 = "100";
const sc_lv<32> update_value_int::ap_const_lv32_5 = "101";
const sc_lv<1> update_value_int::ap_const_lv1_1 = "1";
const sc_lv<32> update_value_int::ap_const_lv32_6 = "110";
const sc_lv<5> update_value_int::ap_const_lv5_0 = "00000";
const sc_lv<32> update_value_int::ap_const_lv32_3 = "11";
const sc_lv<5> update_value_int::ap_const_lv5_11 = "10001";
const sc_lv<5> update_value_int::ap_const_lv5_1 = "1";
const sc_lv<8> update_value_int::ap_const_lv8_0 = "00000000";
const sc_lv<9> update_value_int::ap_const_lv9_1D0 = "111010000";
const bool update_value_int::ap_const_boolean_1 = true;

update_value_int::update_value_int(sc_module_name name) : sc_module(name), mVcdFile(0) {
    p_str12_U = new update_value_int_p_str12("p_str12_U");
    p_str12_U->clk(ap_clk);
    p_str12_U->reset(ap_rst);
    p_str12_U->address0(p_str12_address0);
    p_str12_U->ce0(p_str12_ce0);
    p_str12_U->q0(p_str12_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln123_fu_151_p2);
    sensitive << ( idx );
    sensitive << ( zext_ln122_5_fu_131_p1 );

    SC_METHOD(thread_add_ln132_fu_166_p2);
    sensitive << ( idx_assign_0_in_reg_105 );

    SC_METHOD(thread_add_ln134_9_fu_219_p2);
    sensitive << ( zext_ln134_fu_210_p1 );

    SC_METHOD(thread_add_ln134_fu_213_p2);
    sensitive << ( shl_ln134_fu_198_p2 );
    sensitive << ( shl_ln134_5_fu_204_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln122_reg_251 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln134_fu_177_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( icmp_ln122_reg_251 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln134_fu_177_p2 );

    SC_METHOD(thread_i_fu_145_p2);
    sensitive << ( i_0_i_reg_93 );

    SC_METHOD(thread_icmp_ln122_fu_139_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i_0_i_reg_93 );

    SC_METHOD(thread_icmp_ln123_fu_161_p2);
    sensitive << ( iscsi_connection_parameter_data_q0 );
    sensitive << ( zext_ln122_6_reg_246 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_icmp_ln134_fu_177_p2);
    sensitive << ( iscsi_connection_parameter_data_q0 );
    sensitive << ( icmp_ln122_reg_251 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_icmp_ln138_fu_183_p2);
    sensitive << ( val_r_i );
    sensitive << ( icmp_ln122_reg_251 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( nw_val_0_reg_114 );
    sensitive << ( icmp_ln134_fu_177_p2 );

    SC_METHOD(thread_iscsi_connection_parameter_data_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( sext_ln123_fu_156_p1 );
    sensitive << ( sext_ln134_fu_172_p1 );

    SC_METHOD(thread_iscsi_connection_parameter_data_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_nw_val_fu_229_p2);
    sensitive << ( sext_ln134_5_fu_225_p1 );
    sensitive << ( add_ln134_fu_213_p2 );

    SC_METHOD(thread_p_str12_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln122_fu_126_p1 );

    SC_METHOD(thread_p_str12_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_select_ln138_fu_189_p3);
    sensitive << ( val_r_i );
    sensitive << ( nw_val_0_reg_114 );
    sensitive << ( icmp_ln138_fu_183_p2 );

    SC_METHOD(thread_sext_ln123_fu_156_p1);
    sensitive << ( add_ln123_fu_151_p2 );

    SC_METHOD(thread_sext_ln134_5_fu_225_p1);
    sensitive << ( add_ln134_9_fu_219_p2 );

    SC_METHOD(thread_sext_ln134_fu_172_p1);
    sensitive << ( add_ln132_fu_166_p2 );

    SC_METHOD(thread_shl_ln134_5_fu_204_p2);
    sensitive << ( nw_val_0_reg_114 );

    SC_METHOD(thread_shl_ln134_fu_198_p2);
    sensitive << ( nw_val_0_reg_114 );

    SC_METHOD(thread_val_r_o);
    sensitive << ( val_r_i );
    sensitive << ( icmp_ln122_reg_251 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln134_fu_177_p2 );
    sensitive << ( select_ln138_fu_189_p3 );

    SC_METHOD(thread_val_r_o_ap_vld);
    sensitive << ( icmp_ln122_reg_251 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln134_fu_177_p2 );

    SC_METHOD(thread_zext_ln122_5_fu_131_p1);
    sensitive << ( i_0_i_reg_93 );

    SC_METHOD(thread_zext_ln122_6_fu_135_p1);
    sensitive << ( p_str12_q0 );

    SC_METHOD(thread_zext_ln122_fu_126_p1);
    sensitive << ( i_0_i_reg_93 );

    SC_METHOD(thread_zext_ln134_fu_210_p1);
    sensitive << ( iscsi_connection_par_21_reg_278 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln122_fu_139_p2 );
    sensitive << ( icmp_ln122_reg_251 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln123_fu_161_p2 );
    sensitive << ( icmp_ln134_fu_177_p2 );

    ap_CS_fsm = "0000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "update_value_int_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, iscsi_connection_parameter_data_address0, "(port)iscsi_connection_parameter_data_address0");
    sc_trace(mVcdFile, iscsi_connection_parameter_data_ce0, "(port)iscsi_connection_parameter_data_ce0");
    sc_trace(mVcdFile, iscsi_connection_parameter_data_q0, "(port)iscsi_connection_parameter_data_q0");
    sc_trace(mVcdFile, idx, "(port)idx");
    sc_trace(mVcdFile, val_r_i, "(port)val_r_i");
    sc_trace(mVcdFile, val_r_o, "(port)val_r_o");
    sc_trace(mVcdFile, val_r_o_ap_vld, "(port)val_r_o_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, p_str12_address0, "p_str12_address0");
    sc_trace(mVcdFile, p_str12_ce0, "p_str12_ce0");
    sc_trace(mVcdFile, p_str12_q0, "p_str12_q0");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, zext_ln122_6_fu_135_p1, "zext_ln122_6_fu_135_p1");
    sc_trace(mVcdFile, zext_ln122_6_reg_246, "zext_ln122_6_reg_246");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, icmp_ln122_fu_139_p2, "icmp_ln122_fu_139_p2");
    sc_trace(mVcdFile, icmp_ln122_reg_251, "icmp_ln122_reg_251");
    sc_trace(mVcdFile, i_fu_145_p2, "i_fu_145_p2");
    sc_trace(mVcdFile, i_reg_255, "i_reg_255");
    sc_trace(mVcdFile, add_ln132_fu_166_p2, "add_ln132_fu_166_p2");
    sc_trace(mVcdFile, add_ln132_reg_268, "add_ln132_reg_268");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, iscsi_connection_par_21_reg_278, "iscsi_connection_par_21_reg_278");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, nw_val_fu_229_p2, "nw_val_fu_229_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, i_0_i_reg_93, "i_0_i_reg_93");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, icmp_ln123_fu_161_p2, "icmp_ln123_fu_161_p2");
    sc_trace(mVcdFile, idx_assign_0_in_reg_105, "idx_assign_0_in_reg_105");
    sc_trace(mVcdFile, nw_val_0_reg_114, "nw_val_0_reg_114");
    sc_trace(mVcdFile, zext_ln122_fu_126_p1, "zext_ln122_fu_126_p1");
    sc_trace(mVcdFile, sext_ln123_fu_156_p1, "sext_ln123_fu_156_p1");
    sc_trace(mVcdFile, sext_ln134_fu_172_p1, "sext_ln134_fu_172_p1");
    sc_trace(mVcdFile, icmp_ln134_fu_177_p2, "icmp_ln134_fu_177_p2");
    sc_trace(mVcdFile, select_ln138_fu_189_p3, "select_ln138_fu_189_p3");
    sc_trace(mVcdFile, zext_ln122_5_fu_131_p1, "zext_ln122_5_fu_131_p1");
    sc_trace(mVcdFile, add_ln123_fu_151_p2, "add_ln123_fu_151_p2");
    sc_trace(mVcdFile, icmp_ln138_fu_183_p2, "icmp_ln138_fu_183_p2");
    sc_trace(mVcdFile, shl_ln134_fu_198_p2, "shl_ln134_fu_198_p2");
    sc_trace(mVcdFile, shl_ln134_5_fu_204_p2, "shl_ln134_5_fu_204_p2");
    sc_trace(mVcdFile, zext_ln134_fu_210_p1, "zext_ln134_fu_210_p1");
    sc_trace(mVcdFile, add_ln134_9_fu_219_p2, "add_ln134_9_fu_219_p2");
    sc_trace(mVcdFile, sext_ln134_5_fu_225_p1, "sext_ln134_5_fu_225_p1");
    sc_trace(mVcdFile, add_ln134_fu_213_p2, "add_ln134_fu_213_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

update_value_int::~update_value_int() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete p_str12_U;
}

void update_value_int::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln123_fu_161_p2.read()))) {
        i_0_i_reg_93 = i_reg_255.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_i_reg_93 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln122_fu_139_p2.read(), ap_const_lv1_1))) {
        idx_assign_0_in_reg_105 = idx.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        idx_assign_0_in_reg_105 = add_ln132_reg_268.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln122_fu_139_p2.read(), ap_const_lv1_1))) {
        nw_val_0_reg_114 = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        nw_val_0_reg_114 = nw_val_fu_229_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        add_ln132_reg_268 = add_ln132_fu_166_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_reg_255 = i_fu_145_p2.read();
        icmp_ln122_reg_251 = icmp_ln122_fu_139_p2.read();
        zext_ln122_6_reg_246 = zext_ln122_6_fu_135_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(icmp_ln122_reg_251.read(), ap_const_lv1_1))) {
        iscsi_connection_par_21_reg_278 = iscsi_connection_parameter_data_q0.read();
    }
}

void update_value_int::thread_add_ln123_fu_151_p2() {
    add_ln123_fu_151_p2 = (!zext_ln122_5_fu_131_p1.read().is_01() || !idx.read().is_01())? sc_lv<32>(): (sc_biguint<32>(zext_ln122_5_fu_131_p1.read()) + sc_biguint<32>(idx.read()));
}

void update_value_int::thread_add_ln132_fu_166_p2() {
    add_ln132_fu_166_p2 = (!idx_assign_0_in_reg_105.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(idx_assign_0_in_reg_105.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void update_value_int::thread_add_ln134_9_fu_219_p2() {
    add_ln134_9_fu_219_p2 = (!ap_const_lv9_1D0.is_01() || !zext_ln134_fu_210_p1.read().is_01())? sc_lv<9>(): (sc_bigint<9>(ap_const_lv9_1D0) + sc_biguint<9>(zext_ln134_fu_210_p1.read()));
}

void update_value_int::thread_add_ln134_fu_213_p2() {
    add_ln134_fu_213_p2 = (!shl_ln134_fu_198_p2.read().is_01() || !shl_ln134_5_fu_204_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(shl_ln134_fu_198_p2.read()) + sc_biguint<32>(shl_ln134_5_fu_204_p2.read()));
}

void update_value_int::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void update_value_int::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void update_value_int::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void update_value_int::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void update_value_int::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void update_value_int::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void update_value_int::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void update_value_int::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln134_fu_177_p2.read()) || 
           esl_seteq<1,1,1>(icmp_ln122_reg_251.read(), ap_const_lv1_0))))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void update_value_int::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void update_value_int::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln134_fu_177_p2.read()) || 
          esl_seteq<1,1,1>(icmp_ln122_reg_251.read(), ap_const_lv1_0)))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void update_value_int::thread_i_fu_145_p2() {
    i_fu_145_p2 = (!i_0_i_reg_93.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_0_i_reg_93.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void update_value_int::thread_icmp_ln122_fu_139_p2() {
    icmp_ln122_fu_139_p2 = (!i_0_i_reg_93.read().is_01() || !ap_const_lv5_11.is_01())? sc_lv<1>(): sc_lv<1>(i_0_i_reg_93.read() == ap_const_lv5_11);
}

void update_value_int::thread_icmp_ln123_fu_161_p2() {
    icmp_ln123_fu_161_p2 = (!iscsi_connection_parameter_data_q0.read().is_01() || !zext_ln122_6_reg_246.read().is_01())? sc_lv<1>(): sc_lv<1>(iscsi_connection_parameter_data_q0.read() == zext_ln122_6_reg_246.read());
}

void update_value_int::thread_icmp_ln134_fu_177_p2() {
    icmp_ln134_fu_177_p2 = (!iscsi_connection_parameter_data_q0.read().is_01() || !ap_const_lv8_0.is_01())? sc_lv<1>(): sc_lv<1>(iscsi_connection_parameter_data_q0.read() == ap_const_lv8_0);
}

void update_value_int::thread_icmp_ln138_fu_183_p2() {
    icmp_ln138_fu_183_p2 = (!val_r_i.read().is_01() || !nw_val_0_reg_114.read().is_01())? sc_lv<1>(): (sc_bigint<32>(val_r_i.read()) < sc_bigint<32>(nw_val_0_reg_114.read()));
}

void update_value_int::thread_iscsi_connection_parameter_data_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        iscsi_connection_parameter_data_address0 =  (sc_lv<13>) (sext_ln134_fu_172_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        iscsi_connection_parameter_data_address0 =  (sc_lv<13>) (sext_ln123_fu_156_p1.read());
    } else {
        iscsi_connection_parameter_data_address0 = "XXXXXXXXXXXXX";
    }
}

void update_value_int::thread_iscsi_connection_parameter_data_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        iscsi_connection_parameter_data_ce0 = ap_const_logic_1;
    } else {
        iscsi_connection_parameter_data_ce0 = ap_const_logic_0;
    }
}

void update_value_int::thread_nw_val_fu_229_p2() {
    nw_val_fu_229_p2 = (!sext_ln134_5_fu_225_p1.read().is_01() || !add_ln134_fu_213_p2.read().is_01())? sc_lv<32>(): (sc_bigint<32>(sext_ln134_5_fu_225_p1.read()) + sc_biguint<32>(add_ln134_fu_213_p2.read()));
}

void update_value_int::thread_p_str12_address0() {
    p_str12_address0 =  (sc_lv<5>) (zext_ln122_fu_126_p1.read());
}

void update_value_int::thread_p_str12_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        p_str12_ce0 = ap_const_logic_1;
    } else {
        p_str12_ce0 = ap_const_logic_0;
    }
}

void update_value_int::thread_select_ln138_fu_189_p3() {
    select_ln138_fu_189_p3 = (!icmp_ln138_fu_183_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln138_fu_183_p2.read()[0].to_bool())? val_r_i.read(): nw_val_0_reg_114.read());
}

void update_value_int::thread_sext_ln123_fu_156_p1() {
    sext_ln123_fu_156_p1 = esl_sext<64,32>(add_ln123_fu_151_p2.read());
}

void update_value_int::thread_sext_ln134_5_fu_225_p1() {
    sext_ln134_5_fu_225_p1 = esl_sext<32,9>(add_ln134_9_fu_219_p2.read());
}

void update_value_int::thread_sext_ln134_fu_172_p1() {
    sext_ln134_fu_172_p1 = esl_sext<64,32>(add_ln132_fu_166_p2.read());
}

void update_value_int::thread_shl_ln134_5_fu_204_p2() {
    shl_ln134_5_fu_204_p2 = (!ap_const_lv32_1.is_01())? sc_lv<32>(): nw_val_0_reg_114.read() << (unsigned short)ap_const_lv32_1.to_uint();
}

void update_value_int::thread_shl_ln134_fu_198_p2() {
    shl_ln134_fu_198_p2 = (!ap_const_lv32_3.is_01())? sc_lv<32>(): nw_val_0_reg_114.read() << (unsigned short)ap_const_lv32_3.to_uint();
}

void update_value_int::thread_val_r_o() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(icmp_ln122_reg_251.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln134_fu_177_p2.read()))) {
        val_r_o = select_ln138_fu_189_p3.read();
    } else {
        val_r_o = val_r_i.read();
    }
}

void update_value_int::thread_val_r_o_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(icmp_ln122_reg_251.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln134_fu_177_p2.read()))) {
        val_r_o_ap_vld = ap_const_logic_1;
    } else {
        val_r_o_ap_vld = ap_const_logic_0;
    }
}

void update_value_int::thread_zext_ln122_5_fu_131_p1() {
    zext_ln122_5_fu_131_p1 = esl_zext<32,5>(i_0_i_reg_93.read());
}

void update_value_int::thread_zext_ln122_6_fu_135_p1() {
    zext_ln122_6_fu_135_p1 = esl_zext<8,7>(p_str12_q0.read());
}

void update_value_int::thread_zext_ln122_fu_126_p1() {
    zext_ln122_fu_126_p1 = esl_zext<64,5>(i_0_i_reg_93.read());
}

void update_value_int::thread_zext_ln134_fu_210_p1() {
    zext_ln134_fu_210_p1 = esl_zext<9,8>(iscsi_connection_par_21_reg_278.read());
}

void update_value_int::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln122_fu_139_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln123_fu_161_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln134_fu_177_p2.read()) || 
  esl_seteq<1,1,1>(icmp_ln122_reg_251.read(), ap_const_lv1_0)))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<7>) ("XXXXXXX");
            break;
    }
}

}

