// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module read_from_tcp (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        iscsi_pdu_header_buffer_V_address0,
        iscsi_pdu_header_buffer_V_ce0,
        iscsi_pdu_header_buffer_V_we0,
        iscsi_pdu_header_buffer_V_d0,
        iscsi_pdu_header_buffer_V_address1,
        iscsi_pdu_header_buffer_V_ce1,
        iscsi_pdu_header_buffer_V_we1,
        iscsi_pdu_header_buffer_V_d1,
        inp_stream_V_V_TDATA,
        inp_stream_V_V_TVALID,
        inp_stream_V_V_TREADY
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] iscsi_pdu_header_buffer_V_address0;
output   iscsi_pdu_header_buffer_V_ce0;
output   iscsi_pdu_header_buffer_V_we0;
output  [7:0] iscsi_pdu_header_buffer_V_d0;
output  [5:0] iscsi_pdu_header_buffer_V_address1;
output   iscsi_pdu_header_buffer_V_ce1;
output   iscsi_pdu_header_buffer_V_we1;
output  [7:0] iscsi_pdu_header_buffer_V_d1;
input  [31:0] inp_stream_V_V_TDATA;
input   inp_stream_V_V_TVALID;
output   inp_stream_V_V_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg inp_stream_V_V_TREADY;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_read_byte_array_fu_16_ap_start;
wire    grp_read_byte_array_fu_16_ap_done;
wire    grp_read_byte_array_fu_16_ap_idle;
wire    grp_read_byte_array_fu_16_ap_ready;
wire    grp_read_byte_array_fu_16_stream_ap_uint_32_V_V_TREADY;
wire   [5:0] grp_read_byte_array_fu_16_data_address0;
wire    grp_read_byte_array_fu_16_data_ce0;
wire    grp_read_byte_array_fu_16_data_we0;
wire   [7:0] grp_read_byte_array_fu_16_data_d0;
wire   [5:0] grp_read_byte_array_fu_16_data_address1;
wire    grp_read_byte_array_fu_16_data_ce1;
wire    grp_read_byte_array_fu_16_data_we1;
wire   [7:0] grp_read_byte_array_fu_16_data_d1;
reg    grp_read_byte_array_fu_16_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_read_byte_array_fu_16_ap_start_reg = 1'b0;
end

read_byte_array grp_read_byte_array_fu_16(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_read_byte_array_fu_16_ap_start),
    .ap_done(grp_read_byte_array_fu_16_ap_done),
    .ap_idle(grp_read_byte_array_fu_16_ap_idle),
    .ap_ready(grp_read_byte_array_fu_16_ap_ready),
    .stream_ap_uint_32_V_V_TDATA(inp_stream_V_V_TDATA),
    .stream_ap_uint_32_V_V_TVALID(inp_stream_V_V_TVALID),
    .stream_ap_uint_32_V_V_TREADY(grp_read_byte_array_fu_16_stream_ap_uint_32_V_V_TREADY),
    .data_address0(grp_read_byte_array_fu_16_data_address0),
    .data_ce0(grp_read_byte_array_fu_16_data_ce0),
    .data_we0(grp_read_byte_array_fu_16_data_we0),
    .data_d0(grp_read_byte_array_fu_16_data_d0),
    .data_address1(grp_read_byte_array_fu_16_data_address1),
    .data_ce1(grp_read_byte_array_fu_16_data_ce1),
    .data_we1(grp_read_byte_array_fu_16_data_we1),
    .data_d1(grp_read_byte_array_fu_16_data_d1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_read_byte_array_fu_16_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_read_byte_array_fu_16_ap_start_reg <= 1'b1;
        end else if ((grp_read_byte_array_fu_16_ap_ready == 1'b1)) begin
            grp_read_byte_array_fu_16_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((grp_read_byte_array_fu_16_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_read_byte_array_fu_16_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        inp_stream_V_V_TREADY = grp_read_byte_array_fu_16_stream_ap_uint_32_V_V_TREADY;
    end else begin
        inp_stream_V_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_read_byte_array_fu_16_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign grp_read_byte_array_fu_16_ap_start = grp_read_byte_array_fu_16_ap_start_reg;

assign iscsi_pdu_header_buffer_V_address0 = grp_read_byte_array_fu_16_data_address0;

assign iscsi_pdu_header_buffer_V_address1 = grp_read_byte_array_fu_16_data_address1;

assign iscsi_pdu_header_buffer_V_ce0 = grp_read_byte_array_fu_16_data_ce0;

assign iscsi_pdu_header_buffer_V_ce1 = grp_read_byte_array_fu_16_data_ce1;

assign iscsi_pdu_header_buffer_V_d0 = grp_read_byte_array_fu_16_data_d0;

assign iscsi_pdu_header_buffer_V_d1 = grp_read_byte_array_fu_16_data_d1;

assign iscsi_pdu_header_buffer_V_we0 = grp_read_byte_array_fu_16_data_we0;

assign iscsi_pdu_header_buffer_V_we1 = grp_read_byte_array_fu_16_data_we1;

endmodule //read_from_tcp
