// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module write_key_value_int (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        value_r,
        instance_data_length_i,
        instance_data_length_o,
        instance_data_length_o_ap_vld,
        instance_data_address0,
        instance_data_ce0,
        instance_data_we0,
        instance_data_d0,
        buffer_r_address0,
        buffer_r_ce0,
        buffer_r_we0,
        buffer_r_d0,
        buffer_r_q0
);

parameter    ap_ST_fsm_state1 = 41'd1;
parameter    ap_ST_fsm_state2 = 41'd2;
parameter    ap_ST_fsm_state3 = 41'd4;
parameter    ap_ST_fsm_state4 = 41'd8;
parameter    ap_ST_fsm_state5 = 41'd16;
parameter    ap_ST_fsm_state6 = 41'd32;
parameter    ap_ST_fsm_state7 = 41'd64;
parameter    ap_ST_fsm_state8 = 41'd128;
parameter    ap_ST_fsm_state9 = 41'd256;
parameter    ap_ST_fsm_state10 = 41'd512;
parameter    ap_ST_fsm_state11 = 41'd1024;
parameter    ap_ST_fsm_state12 = 41'd2048;
parameter    ap_ST_fsm_state13 = 41'd4096;
parameter    ap_ST_fsm_state14 = 41'd8192;
parameter    ap_ST_fsm_state15 = 41'd16384;
parameter    ap_ST_fsm_state16 = 41'd32768;
parameter    ap_ST_fsm_state17 = 41'd65536;
parameter    ap_ST_fsm_state18 = 41'd131072;
parameter    ap_ST_fsm_state19 = 41'd262144;
parameter    ap_ST_fsm_state20 = 41'd524288;
parameter    ap_ST_fsm_state21 = 41'd1048576;
parameter    ap_ST_fsm_state22 = 41'd2097152;
parameter    ap_ST_fsm_state23 = 41'd4194304;
parameter    ap_ST_fsm_state24 = 41'd8388608;
parameter    ap_ST_fsm_state25 = 41'd16777216;
parameter    ap_ST_fsm_state26 = 41'd33554432;
parameter    ap_ST_fsm_state27 = 41'd67108864;
parameter    ap_ST_fsm_state28 = 41'd134217728;
parameter    ap_ST_fsm_state29 = 41'd268435456;
parameter    ap_ST_fsm_state30 = 41'd536870912;
parameter    ap_ST_fsm_state31 = 41'd1073741824;
parameter    ap_ST_fsm_state32 = 41'd2147483648;
parameter    ap_ST_fsm_state33 = 41'd4294967296;
parameter    ap_ST_fsm_state34 = 41'd8589934592;
parameter    ap_ST_fsm_state35 = 41'd17179869184;
parameter    ap_ST_fsm_state36 = 41'd34359738368;
parameter    ap_ST_fsm_state37 = 41'd68719476736;
parameter    ap_ST_fsm_state38 = 41'd137438953472;
parameter    ap_ST_fsm_state39 = 41'd274877906944;
parameter    ap_ST_fsm_state40 = 41'd549755813888;
parameter    ap_ST_fsm_state41 = 41'd1099511627776;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] value_r;
input  [31:0] instance_data_length_i;
output  [31:0] instance_data_length_o;
output   instance_data_length_o_ap_vld;
output  [12:0] instance_data_address0;
output   instance_data_ce0;
output   instance_data_we0;
output  [7:0] instance_data_d0;
output  [4:0] buffer_r_address0;
output   buffer_r_ce0;
output   buffer_r_we0;
output  [7:0] buffer_r_d0;
input  [7:0] buffer_r_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] instance_data_length_o;
reg instance_data_length_o_ap_vld;
reg[12:0] instance_data_address0;
reg instance_data_ce0;
reg instance_data_we0;
reg[7:0] instance_data_d0;
reg[4:0] buffer_r_address0;
reg buffer_r_ce0;
reg buffer_r_we0;
reg[7:0] buffer_r_d0;

(* fsm_encoding = "none" *) reg   [40:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [4:0] p_str924_address0;
reg    p_str924_ce0;
wire   [6:0] p_str924_q0;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln168_fu_236_p2;
reg   [0:0] icmp_ln168_reg_430;
wire   [4:0] i_fu_242_p2;
reg   [4:0] i_reg_434;
wire   [31:0] grp_fu_219_p2;
reg   [31:0] add_ln171_reg_439;
wire    ap_CS_fsm_state3;
wire   [31:0] zext_ln183_fu_268_p1;
wire   [64:0] mul_ln185_fu_288_p2;
reg   [64:0] mul_ln185_reg_455;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln183_fu_272_p2;
reg   [0:0] tmp_8_reg_460;
reg   [28:0] tmp_reg_466;
wire   [31:0] select_ln185_4_fu_347_p3;
reg   [31:0] select_ln185_4_reg_471;
wire    ap_CS_fsm_state5;
wire   [31:0] length_fu_369_p2;
wire    ap_CS_fsm_state39;
wire   [31:0] length_6_fu_386_p2;
reg   [31:0] length_6_reg_484;
wire    ap_CS_fsm_state40;
wire   [0:0] icmp_ln187_fu_380_p2;
wire    ap_CS_fsm_state41;
reg   [4:0] i_0_i_reg_142;
reg   [31:0] ap_phi_mux_p_0_ph_phi_fu_156_p4;
wire   [0:0] icmp_ln180_fu_263_p2;
reg   [0:0] ap_phi_mux_length_1_ph_phi_fu_167_p4;
reg  signed [31:0] p_0_reg_175;
reg  signed [31:0] length_1_reg_186;
reg  signed [31:0] instance_data_length_16_reg_196;
reg   [31:0] length_2_reg_205;
wire   [63:0] zext_ln168_fu_231_p1;
wire  signed [63:0] sext_ln169_fu_253_p1;
wire  signed [63:0] sext_ln171_fu_258_p1;
wire  signed [63:0] sext_ln184_fu_375_p1;
wire   [63:0] zext_ln188_fu_392_p1;
wire  signed [63:0] sext_ln190_fu_409_p1;
wire  signed [63:0] sext_ln188_fu_414_p1;
wire   [31:0] add_ln190_fu_397_p2;
wire   [7:0] zext_ln168_2_fu_248_p1;
wire   [7:0] zext_ln184_fu_364_p1;
wire  signed [31:0] grp_fu_219_p0;
wire  signed [31:0] sext_ln169_fu_253_p0;
wire  signed [31:0] sext_ln171_fu_258_p0;
wire   [4:0] grp_fu_278_p1;
wire  signed [31:0] mul_ln185_fu_288_p1;
wire   [64:0] sub_ln185_fu_312_p2;
wire   [28:0] tmp_9_fu_317_p4;
wire  signed [31:0] sext_ln185_7_fu_327_p1;
wire  signed [31:0] sext_ln185_8_fu_331_p1;
wire   [31:0] select_ln185_fu_334_p3;
wire   [31:0] sub_ln185_4_fu_341_p2;
wire   [5:0] grp_fu_278_p2;
wire   [5:0] trunc_ln184_fu_354_p1;
wire   [5:0] add_ln184_fu_358_p2;
wire  signed [31:0] sext_ln188_fu_414_p0;
reg    grp_fu_278_ap_start;
wire    grp_fu_278_ap_done;
reg   [40:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 41'd1;
end

update_value_int_p_str12 #(
    .DataWidth( 7 ),
    .AddressRange( 18 ),
    .AddressWidth( 5 ))
p_str924_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_str924_address0),
    .ce0(p_str924_ce0),
    .q0(p_str924_q0)
);

iscsi_interface_srem_32s_5ns_6_36_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 6 ))
iscsi_interface_srem_32s_5ns_6_36_seq_1_U102(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_278_ap_start),
    .done(grp_fu_278_ap_done),
    .din0(p_0_reg_175),
    .din1(grp_fu_278_p1),
    .ce(1'b1),
    .dout(grp_fu_278_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln168_reg_430 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        i_0_i_reg_142 <= i_reg_434;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_i_reg_142 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln183_fu_272_p2 == 1'd1))) begin
        instance_data_length_16_reg_196 <= add_ln171_reg_439;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        instance_data_length_16_reg_196 <= grp_fu_219_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln168_reg_430 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        length_1_reg_186 <= zext_ln183_fu_268_p1;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        length_1_reg_186 <= length_fu_369_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln183_fu_272_p2 == 1'd1))) begin
        length_2_reg_205 <= length_1_reg_186;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        length_2_reg_205 <= length_6_reg_484;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln168_reg_430 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        p_0_reg_175 <= ap_phi_mux_p_0_ph_phi_fu_156_p4;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        p_0_reg_175 <= select_ln185_4_reg_471;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln168_reg_430 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        add_ln171_reg_439 <= grp_fu_219_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_434 <= i_fu_242_p2;
        icmp_ln168_reg_430 <= icmp_ln168_fu_236_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state40) & (icmp_ln187_fu_380_p2 == 1'd1))) begin
        length_6_reg_484 <= length_6_fu_386_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln183_fu_272_p2 == 1'd0))) begin
        mul_ln185_reg_455 <= mul_ln185_fu_288_p2;
        tmp_8_reg_460 <= p_0_reg_175[32'd31];
        tmp_reg_466 <= {{mul_ln185_fu_288_p2[64:36]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        select_ln185_4_reg_471 <= select_ln185_4_fu_347_p3;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state40) & (icmp_ln187_fu_380_p2 == 1'd0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln168_reg_430 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        if ((icmp_ln180_fu_263_p2 == 1'd1)) begin
            ap_phi_mux_length_1_ph_phi_fu_167_p4 = 1'd1;
        end else if ((icmp_ln180_fu_263_p2 == 1'd0)) begin
            ap_phi_mux_length_1_ph_phi_fu_167_p4 = 1'd0;
        end else begin
            ap_phi_mux_length_1_ph_phi_fu_167_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_length_1_ph_phi_fu_167_p4 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln168_reg_430 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        if ((icmp_ln180_fu_263_p2 == 1'd1)) begin
            ap_phi_mux_p_0_ph_phi_fu_156_p4 = 32'd0;
        end else if ((icmp_ln180_fu_263_p2 == 1'd0)) begin
            ap_phi_mux_p_0_ph_phi_fu_156_p4 = value_r;
        end else begin
            ap_phi_mux_p_0_ph_phi_fu_156_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_p_0_ph_phi_fu_156_p4 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state40) & (icmp_ln187_fu_380_p2 == 1'd0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state40)) begin
        buffer_r_address0 = zext_ln188_fu_392_p1;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        buffer_r_address0 = sext_ln184_fu_375_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buffer_r_address0 = 5'd0;
    end else begin
        buffer_r_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state3))) begin
        buffer_r_ce0 = 1'b1;
    end else begin
        buffer_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        buffer_r_d0 = zext_ln184_fu_364_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buffer_r_d0 = 8'd48;
    end else begin
        buffer_r_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state39) | ((icmp_ln168_reg_430 == 1'd1) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln180_fu_263_p2 == 1'd1)))) begin
        buffer_r_we0 = 1'b1;
    end else begin
        buffer_r_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln183_fu_272_p2 == 1'd0))) begin
        grp_fu_278_ap_start = 1'b1;
    end else begin
        grp_fu_278_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        instance_data_address0 = sext_ln188_fu_414_p1;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        instance_data_address0 = sext_ln190_fu_409_p1;
    end else if (((icmp_ln168_reg_430 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        instance_data_address0 = sext_ln171_fu_258_p1;
    end else if (((icmp_ln168_reg_430 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        instance_data_address0 = sext_ln169_fu_253_p1;
    end else begin
        instance_data_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state40) | ((icmp_ln168_reg_430 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln168_reg_430 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        instance_data_ce0 = 1'b1;
    end else begin
        instance_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        instance_data_d0 = buffer_r_q0;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        instance_data_d0 = 8'd0;
    end else if (((icmp_ln168_reg_430 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        instance_data_d0 = 8'd61;
    end else if (((icmp_ln168_reg_430 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        instance_data_d0 = zext_ln168_2_fu_248_p1;
    end else begin
        instance_data_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state40) & (icmp_ln187_fu_380_p2 == 1'd0))) begin
        instance_data_length_o = add_ln190_fu_397_p2;
    end else if (((1'b1 == ap_CS_fsm_state41) | ((icmp_ln168_reg_430 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln168_reg_430 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        instance_data_length_o = grp_fu_219_p2;
    end else begin
        instance_data_length_o = instance_data_length_i;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state41) | ((1'b1 == ap_CS_fsm_state40) & (icmp_ln187_fu_380_p2 == 1'd0)) | ((icmp_ln168_reg_430 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln168_reg_430 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        instance_data_length_o_ap_vld = 1'b1;
    end else begin
        instance_data_length_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state41) | ((1'b1 == ap_CS_fsm_state40) & (icmp_ln187_fu_380_p2 == 1'd0)) | ((icmp_ln168_reg_430 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln168_reg_430 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        instance_data_we0 = 1'b1;
    end else begin
        instance_data_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_str924_ce0 = 1'b1;
    end else begin
        p_str924_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln168_reg_430 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln183_fu_272_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state40;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state40 : begin
            if (((1'b1 == ap_CS_fsm_state40) & (icmp_ln187_fu_380_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state41;
            end
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln184_fu_358_p2 = ($signed(6'd48) + $signed(trunc_ln184_fu_354_p1));

assign add_ln190_fu_397_p2 = ($signed(instance_data_length_16_reg_196) + $signed(32'd1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign grp_fu_219_p0 = instance_data_length_i;

assign grp_fu_219_p2 = ($signed(grp_fu_219_p0) + $signed(32'd1));

assign grp_fu_278_p1 = 32'd10;

assign i_fu_242_p2 = (i_0_i_reg_142 + 5'd1);

assign icmp_ln168_fu_236_p2 = ((i_0_i_reg_142 == 5'd17) ? 1'b1 : 1'b0);

assign icmp_ln180_fu_263_p2 = ((value_r == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln183_fu_272_p2 = ((p_0_reg_175 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln187_fu_380_p2 = (($signed(length_2_reg_205) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign length_6_fu_386_p2 = ($signed(length_2_reg_205) + $signed(32'd4294967295));

assign length_fu_369_p2 = ($signed(32'd1) + $signed(length_1_reg_186));

assign mul_ln185_fu_288_p1 = p_0_reg_175;

assign mul_ln185_fu_288_p2 = ($signed({{1'b0}, {65'd6871947674}}) * $signed(mul_ln185_fu_288_p1));

assign p_str924_address0 = zext_ln168_fu_231_p1;

assign select_ln185_4_fu_347_p3 = ((tmp_8_reg_460[0:0] === 1'b1) ? sub_ln185_4_fu_341_p2 : sext_ln185_8_fu_331_p1);

assign select_ln185_fu_334_p3 = ((tmp_8_reg_460[0:0] === 1'b1) ? sext_ln185_7_fu_327_p1 : sext_ln185_8_fu_331_p1);

assign sext_ln169_fu_253_p0 = instance_data_length_i;

assign sext_ln169_fu_253_p1 = sext_ln169_fu_253_p0;

assign sext_ln171_fu_258_p0 = instance_data_length_i;

assign sext_ln171_fu_258_p1 = sext_ln171_fu_258_p0;

assign sext_ln184_fu_375_p1 = length_1_reg_186;

assign sext_ln185_7_fu_327_p1 = $signed(tmp_9_fu_317_p4);

assign sext_ln185_8_fu_331_p1 = $signed(tmp_reg_466);

assign sext_ln188_fu_414_p0 = instance_data_length_i;

assign sext_ln188_fu_414_p1 = sext_ln188_fu_414_p0;

assign sext_ln190_fu_409_p1 = instance_data_length_16_reg_196;

assign sub_ln185_4_fu_341_p2 = (32'd0 - select_ln185_fu_334_p3);

assign sub_ln185_fu_312_p2 = (65'd0 - mul_ln185_reg_455);

assign tmp_9_fu_317_p4 = {{sub_ln185_fu_312_p2[64:36]}};

assign trunc_ln184_fu_354_p1 = grp_fu_278_p2[5:0];

assign zext_ln168_2_fu_248_p1 = p_str924_q0;

assign zext_ln168_fu_231_p1 = i_0_i_reg_142;

assign zext_ln183_fu_268_p1 = ap_phi_mux_length_1_ph_phi_fu_167_p4;

assign zext_ln184_fu_364_p1 = add_ln184_fu_358_p2;

assign zext_ln188_fu_392_p1 = length_6_fu_386_p2;

endmodule //write_key_value_int
